@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE5MjY5NzV9.0rIEaFbAitRk56JflZlpuS1hSQGDVbcIbkZRhvCM55w

### PRODUCTS INDEX ###
GET http://localhost:3000/products.json

### PRODUCTS SHOW ###
GET http://localhost:3000/products/1.json

### PRODUCTS CREATE ###
POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "test",
  "price": 2,
  "url": "test image url",
  "description": "test description"
}

### PRODUCTS UPDATE ###
PATCH http://localhost:3000/products/4.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Conditioner",
  "price": 12
}

### PRODUCTS DESTROY ###
DELETE http://localhost:3000/products/4.json

### Users create (signup)
  POST http://localhost:3000/users
  Content-Type: application/json

  {
    "name": "Test name",
    "email": "test@test.com",
    "password": "password",
    "password_confirmation": "password"
  }

### Sessions create (login)
  POST http://localhost:3000/sessions
  Content-Type: application/json

  {
    "email": "vic@test.com",
    "password": "password"
  }

### Photos create
POST http://localhost:3000/photos
Authorization: Bearer {{jwt}}
Content-Type: application/json

  {
    "name": "Test name",
    "width": 640,
    "height": 480
  }

### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json



### Orders Create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### ORDERS SHOW ###
GET http://localhost:3000/orders/4.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### CARTED PRODUCTS INDEX ###
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Carted Product Create ###
POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 3
}

### CARTED PRODUCT DESTROY
DELETE http://localhost:3000/carted_products/6.json
Authorization: Bearer {{jwt}}