### PRODUCTS INDEX ###
GET http://localhost:3000/products.json

### PRODUCTS SHOW ###
GET http://localhost:3000/products/1.json

### PRODUCTS CREATE ###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Shampoo",
  "price": -9,
  "url": "https://images.squarespace-cdn.com/content/v1/5daa3d54e0f35e4910d94559/1625249558930-OQA9RK3Q7N4JBH5O5D2S/IMG_4212.jpg?format=1500w",
  "description": "This formula is sulfate free and can be used daily to ensure hair health and stimulation."
}

### PRODUCTS UPDATE ###
PATCH http://localhost:3000/products/4.json
Content-Type: application/json

{
  "name": "Conditioner",
  "price": 12
}

### PRODUCTS DESTROY ###
DELETE http://localhost:3000/products/4.json

### Users create (signup)
  POST http://localhost:3000/users
  Content-Type: application/json

  {
    "name": "Test name",
    "email": "vic@test.com",
    "password": "password",
    "password_confirmation": "password"
  }

### Sessions create (login)
  POST http://localhost:3000/sessions
  Content-Type: application/json

  {
    "email": "vic@test.com",
    "password": "password"
  }

### Photos create
POST http://localhost:3000/photos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json

  {
    "name": "Test name",
    "width": 640,
    "height": 480
  }



### Orders Create
POST http://localhost:3000/orders.json
Content-Type: application/json


  {
    "product_id": 1,
    "quantity": 1
  }

### ORDERS SHOW ###
GET http://localhost:3000/orders/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzA3NzE2NjZ9.NvShSP8jtgpMP5HvkjZPIoD_tJ_WnWaxT1eOmsvAKNk

### PRODUCTS INDEX ###
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzA3NzE2NjZ9.NvShSP8jtgpMP5HvkjZPIoD_tJ_WnWaxT1eOmsvAKNk

### Show Order
get http://localhost:3000/orders/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzA3NzE2NjZ9.NvShSP8jtgpMP5HvkjZPIoD_tJ_WnWaxT1eOmsvAKNk